In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import joblib

In [2]:
df = pd.read_csv("../data/TSLA.csv")

df['Date'] = pd.to_datetime(df['Date'])
df.set_index('Date', inplace=True)

df.head()

                 Open   High        Low      Close  Adj Close    Volume
Date
2010-06-29  19.000000  25.00  17.540001  23.889999  23.889999  18766300
2010-06-30  25.790001  30.42  23.299999  23.830000  23.830000  17187100
2010-07-01  25.000000  25.92  20.270000  21.959999  21.959999   8218800
2010-07-02  23.000000  23.10  18.709999  19.200001  19.200001   5139800
2010-07-06  20.000000  20.00  15.830000  16.110001  16.110001   6866900

In [3]:
data = df[['Close']]
data.head()

                Close
Date
2010-06-29  23.889999
2010-06-30  23.830000
2010-07-01  21.959999
2010-07-02  19.200001
2010-07-06  16.110001

In [4]:
scaler = MinMaxScaler(feature_range=(0,1))
scaled_data = scaler.fit_transform(data)

scaled_data[:5]

array([[0.01058623],
       [0.01050772],
       [0.00806072],
       [0.0044491 ],
       [0.00040565]])

In [5]:
joblib.dump(scaler, "../models/scaler.pkl")

['../models/scaler.pkl']

In [6]:
train_size = int(len(scaled_data) * 0.8)

train_data = scaled_data[:train_size]
test_data = scaled_data[train_size-60:]

In [7]:
def create_sequences(data, seq_length=60):
    X = []
    Y = []

    for i in range(seq_length, len(data)):
        X.append(data[i-seq_length:i])
        Y.append(data[i])

    return np.array(X), np.array(Y)

X_train, Y_train = create_sequences(train_data)
X_test, Y_test = create_sequences(test_data)

In [8]:
print(f"X_train: {X_train.shape}")
print(f"Y_train: {Y_train.shape}\n")

print(f"X_test: {X_test.shape}")
print(f"Y_test: {Y_test.shape}")

X_train: (1872, 60, 1)
Y_train: (1872, 1)

X_test: (484, 60, 1)
Y_test: (484, 1)

In [9]:
np.save("../data/X_train.npy", X_train)
np.save("../data/Y_train.npy", Y_train)
np.save("../data/X_test.npy", X_test)
np.save("../data/y_test.npy", Y_test)